version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ arch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ arch }}-{{ checksum "build.gradle" }}

  save_gradle_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ arch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ arch }}-{{ checksum "build.gradle" }}

jobs:
  android-test:
    machine:
      image: android:2022.12.1
    resource_class: large
    steps:
      - checkout
      - run: python3 scripts/generateKsPropFile.py
      - restore_gradle_cache
      - run: sdkmanager --list
      - run: (yes || true) | sdkmanager "tools" "platform-tools" "build-tools;33.0.2" "platforms;android-33" "system-images;android-30;google_atd;x86"
      - run: (yes || true) | sdkmanager --licenses
      - run: ./gradlew generateGoogleServicesJson
      - run: ./gradlew assembleDebug --stacktrace
      - run: ./gradlew pixel2api30DebugAndroidTest --stacktrace
      - run: ./gradlew testDebugUnitTest --stacktrace
      - run: ./gradlew jacocoTestReport --stacktrace
      - save_gradle_cache
      - run:
          name: Analyze on SonarCloud
          command: ./gradlew lintDebug sonar
      - codecov/upload:
          file: app/build/mergedReportDir/jacocoTestReport/jacocoTestReport.xml
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest
      - store_artifacts:
          path: app/build/mergedReportDir

workflows:
  workflow:
    jobs:
      - android-test:
          context: SonarCloud
