name: Android CI

on: [push]

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Ruby to install fastlane
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: generate ksProp file
      run: python scripts/generateKsPropFile.py
    - name: create google-services.json file
      run: cat app/google-services.json | base64
    - name: update google-services.json file
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > app/google-services.json
    - name: setup fastlane
      run: bundle install
    - name: run unit tests
      run: bundle exec fastlane android run_unit_tests
    - name: Unit tests results
      uses: actions/upload-artifact@v1
      with:
        name: unit-test-results
        path: app/build/reports/tests/testDebugUnitTest/index.html

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: generate ksProp file
        run: python scripts/generateKsPropFile.py
      - name: create google-services.json file
        run: cat app/google-services.json | base64
      - name: update google-services.json file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > app/google-services.json
      - name: Lint
        run: bash ./gradlew lintDebug
      - name: Lint results
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/reports/lint-results-debug.html

  ui-test:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: generate ksProp file
        run: python scripts/generateKsPropFile.py
      - name: create google-services.json file
        run: cat app/google-services.json | base64
      - name: update google-services.json file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > app/google-services.json
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
